// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJ_8NYGs2IbA9c3JOIR1fECLLa-ajEQQ',
    appId: '1:364152217027:web:2f1a6e1720b8ad0ecbf176',
    messagingSenderId: '364152217027',
    projectId: 'jenkisproject',
    authDomain: 'jenkisproject.firebaseapp.com',
    storageBucket: 'jenkisproject.appspot.com',
    measurementId: 'G-NP90J84E73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGSE3xhfQBmx9_d1Edz3w5bQELNw2W8Q',
    appId: '1:364152217027:android:bcba8052e846d4b0cbf176',
    messagingSenderId: '364152217027',
    projectId: 'jenkisproject',
    storageBucket: 'jenkisproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-L1RgW9xkvQckA0aW4DA4Z4PnpY3EJk',
    appId: '1:364152217027:ios:ab5c39a9ab51bc21cbf176',
    messagingSenderId: '364152217027',
    projectId: 'jenkisproject',
    storageBucket: 'jenkisproject.appspot.com',
    iosClientId: '364152217027-kokond2823rp70d7agfdcvdna69bt6pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectWithJenkis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-L1RgW9xkvQckA0aW4DA4Z4PnpY3EJk',
    appId: '1:364152217027:ios:ab5c39a9ab51bc21cbf176',
    messagingSenderId: '364152217027',
    projectId: 'jenkisproject',
    storageBucket: 'jenkisproject.appspot.com',
    iosClientId: '364152217027-kokond2823rp70d7agfdcvdna69bt6pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectWithJenkis',
  );
}
